# Generated by Django 2.2 on 2020-08-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_authuser_usermovie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='plot',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
